### ISSUE TITLE
Improve ripple animation

### ISSUE THREAD

**Issue by mistermantas** [rodymol123/MaterialCraft#3]
## Why

It’s not natural: the animation is slow and originates from the center which looks odd.

[Demo](https://codepen.io/mvilcis/pen/vgELXz)

## Note

There’s one drawback: the element must be displayed as `block` or `inline-block`. I think this applies to that other solution though nevertheless.

## How

```css
@mixin ripple {
  position: relative;
  overflow: hidden;

  &:active::after {
    padding-top: 0;
    padding-left: 0;
    margin-top: 0;
    margin-left: 0;
    opacity: 1;
    transition: 0s;
  }

  &::after {
    content: “”;
    display: block;
    background: rgba($bold-text-color, 0.6);
    color: #fff;
    position: absolute;
    border-radius: 50%;
    padding-top: 240%;
    padding-left: 240%;
    margin-top: -120%;
    margin-left: -120%;
    opacity: 0;
    transition: all $material-design-transition;
  }
}
```
